### PR TITLE
Replace bow + crossbow mixins with Projectile Damage attribute

### PR DESCRIPTION
**Pull request by TheWinABagel**
Also adds a dependency for projectile damage attribute
Damage is the same as it was before

### CODE REVIEW

**Comment by Globox1997** [comment]
Not a fan to have more dependencies...

**Comment by NolanHewitt** [comment]
Would love to see this be added! Very nice QOL change if added along side Ranged Weapon API to make the bow/crossbow stats visual to players.

Actually, Ranged Weapon API seems to be the successor to Projectile Damage Attribute. Updating this PR to that instead would be perfection if possible. I don’t think both are necessary.

**Comment by TheWinABagel** [comment]
Api is deprecated

**Comment by NolanHewitt** [comment]
Ranged Weapon API isn't and it's essentially the same thing.

**Pull request closed without merging**
